### ISSUE TITLE
Support for multiple IPs

### ISSUE THREAD

**Issue by Slind14** [Dynitios/AutoKeylight#1]
Hi Dynitios,

would you consider adding support for multiple IPs/key lights?

**Comment by thomas-tcj** [comment]
Ah, apologies for the late response, apparently I'm not notified when new issues are created here.

I don't plan on adding new features to this project. However @astutejoe has made a C# clone of this project that does support multiple IP's. You can find his version here: https://github.com/astutejoe/AutoKeyLight.
